# Generated by Django 3.1.7 on 2021-09-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
