# Generated by Django 3.1.7 on 2021-10-09 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datapp', '0002_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='city',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='firstname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='sign',
            old_name='lastname',
            new_name='pass2',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='gender',
        ),
        migrations.AddField(
            model_name='sign',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
