# Generated by Django 3.1.7 on 2021-10-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapp', '0003_auto_20211010_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
