# Generated by Django 3.1.7 on 2021-10-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapp', '0004_delete_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='video',
            name='phone',
        ),
    ]
