# Generated by Django 3.1.7 on 2021-10-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapp', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
